import { Place } from "../_schemas";

export const DEFAULT_PLACES_VALUES: Partial<Place> = {
  name: "",
  description: "",
  address: "",
  landmarks: "",
  city: "",
  state: "",
  country: "",
  longitude: undefined,
  latitude: undefined,
  placeType: "HOTEL",
  emails: [],
  phoneNumbers: [],
  status: "PUBLISHED",
  coverImage: undefined,
  environmentalSafetyPolicy: undefined,
  privacyPolicy: undefined,
  disclaimers: undefined,
  ownershipDocument: undefined,
  ownershipVideo: undefined,
};

export const PLACE_TYPES = [
  { label: "Hotel", value: "HOTEL" },
  { label: "Short Let", value: "SHORT_LET" },
  { label: "Beach Resort", value: "BEACH_RESORT" },
  { label: "Recreation Center", value: "RECREATION_CENTER" },
  { label: "Business Hub", value: "BUSINESS_HUB" },
  { label: "Stadium", value: "STADIUM" },
  { label: "Sport Facility", value: "SPORT_FACILITY" },
  { label: "Country Club", value: "COUNTRY_CLUB" },
  { label: "Sport Recreation Club", value: "SPORT_RECREATION_CLUB" },
  { label: "Hospital", value: "HOSPITAL" },
  { label: "Clinic", value: "CLINIC" },
  { label: "Pharmacy", value: "PHARMACY" },
  { label: "Spa Wellness Center", value: "SPA_WELLNESS_CENTER" },
  { label: "Gym", value: "GYM" },
  { label: "Studio", value: "STUDIO" },
  { label: "Airport", value: "AIRPORT" },
  { label: "Rail Station", value: "RAIL_STATION" },
  { label: "Road Transport Hub", value: "ROAD_TRANSPORT_HUB" },
  { label: "Water Transport Hub", value: "WATER_TRANSPORT_HUB" },
  { label: "Religious Centre", value: "RELIGIOUS_CENTRE" },
  { label: "Police Station", value: "POLICE_STATION" },
  { label: "Court", value: "COURT" },
  { label: "Military Barracks", value: "MILITARY_BARRACKS" },
  { label: "Bank", value: "BANK" },
  { label: "Strip Club", value: "STRIP_CLUB" },
];
