import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/providers/redux-provider";

export const metadata: Metadata = {
  title: "SpinStrip",
  description: "Generated by SpinStrip",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-sf-pro bg-background h-full text-secondary-text antialiased`}
      >
        <ReduxProvider>
          {children}
          <Toaster
            position="bottom-right"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#EBE2FF",
                color: "#6932E2",
                fontWeight: "500",
              },
            }}
          />
        </ReduxProvider>
      </body>
    </html>
  );
}
